### ISSUE TITLE
Zero-padding in documentation

### ISSUE THREAD

**Issue by josephbeaver** [elenam/SortingCompetitionMaterials2015#1]
In the README file, the first comparison example's n1 and n2 values are only shown as having 8 decimal places each, rather than 9.

**Comment by elenam** [comment]
Not anymore :-) Thanks for pointing this out!

On Thu, Oct 8, 2015 at 9:10 AM, Joseph Beaver notifications@github.com
wrote:

> In the README file, the first comparison example's n1 and n2 values are
> only shown as having 8 decimal places each, rather than 9.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/elenam/SortingCompetitionMaterials2015/issues/1.

## 

Dr. Elena Machkasova
Associate Professor of Computer Science
Division of Science and Mathematics
University of Minnesota, Morris
Office: Sci 2325
(320) 589-6308
http://cda.morris.umn.edu/~elenam/
